package apoy2k.robby.model.predef.board

import apoy2k.robby.model.Direction
import apoy2k.robby.model.Field
import apoy2k.robby.model.FieldType

fun generateChopShopBoard() = listOf(
    listOf(
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(FieldType.BELT, Direction.DOWN),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldType.REPAIR)
    ),
    listOf(
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.LASER_2, Direction.UP),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT, Direction.UP),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.HOLE),
        Field.new(),
    ),
    listOf(
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.REPAIR_MOD),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(FieldType.LASER, Direction.RIGHT),
        Field.new(FieldType.ROTATE, Direction.LEFT),
        Field.new(FieldType.ROTATE, Direction.RIGHT),
        Field.new(),
        Field.new(),
        Field.new(FieldType.WALL, Direction.RIGHT),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(FieldType.WALL, Direction.RIGHT)
    ),
    listOf(
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
        Field.new(FieldType.BELT_2, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(),
        Field.new(FieldType.ROTATE, Direction.RIGHT),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.BELT_2, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.RIGHT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldType.HOLE),
        Field.new(FieldType.ROTATE, Direction.LEFT),
        Field.new(),
        Field.new(),
        Field.new(FieldType.REPAIR_MOD),
        Field.new(FieldType.BELT, Direction.DOWN),
        Field.new(FieldType.WALL, Direction.LEFT, Direction.UP),
        Field.new(FieldType.BELT_2, Direction.RIGHT, Direction.UP),
        Field.new(FieldType.BELT_2, Direction.LEFT),
        Field.new(FieldType.BELT_2, Direction.LEFT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.LASER_2, Direction.DOWN),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldType.ROTATE, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(FieldType.BELT, Direction.RIGHT),
        Field.new(FieldType.BELT, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(FieldType.LASER, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.HOLE),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.FLAG),
    ),
    listOf(
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.ROTATE, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.LASER, Direction.LEFT),
        Field.new(FieldType.ROTATE, Direction.RIGHT),
        Field.new(FieldType.WALL, Direction.RIGHT),
        Field.new(),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT),
    ),
    listOf(
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.HOLE),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(FieldType.FLAG),
        Field.new(),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(FieldType.REPAIR_MOD),
        Field.new(FieldType.HOLE),
        Field.new(FieldType.BELT, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldType.WALL, Direction.RIGHT),
    ),
    listOf(
        Field.new(),
        Field.new(FieldType.FLAG),
        Field.new(),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
    ),
    listOf(
        Field.new(FieldType.REPAIR),
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldType.FLAG),
        Field.new(FieldType.BELT, Direction.UP),
        Field.new(),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldType.WALL, Direction.UP),
        Field.new(),
        Field.new(),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
    ),
    listOf(
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldType.WALL, Direction.LEFT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldType.WALL, Direction.DOWN),
        Field.new(),
        Field.new(),
    )
)
