package apoy2k.robby.model.predef.board

import apoy2k.robby.model.Direction
import apoy2k.robby.model.Field
import apoy2k.robby.model.FieldElement

fun generateChopShopBoard() = listOf(
    listOf(
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(FieldElement.BELT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldElement.REPAIR)
    ),
    listOf(
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.LASER_2, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.HOLE),
        Field.new(),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldElement.REPAIR_MOD),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(FieldElement.LASER, Direction.LEFT),
        Field.new(FieldElement.ROTATE, Direction.LEFT),
        Field.new(FieldElement.ROTATE, Direction.RIGHT),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.RIGHT)
    ),
    listOf(
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.ROTATE, Direction.RIGHT),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.BELT_2, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.RIGHT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldElement.HOLE),
        Field.new(FieldElement.ROTATE, Direction.LEFT),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.REPAIR_MOD),
        Field.new(FieldElement.BELT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.LEFT),
        Field.new(FieldElement.BELT_2, Direction.LEFT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.LASER_2, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.ROTATE, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(FieldElement.LASER, Direction.DOWN),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.HOLE),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.FLAG_1),
    ),
    listOf(
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.ROTATE, Direction.LEFT),
        Field.new(),
        Field.new(FieldElement.LASER, Direction.RIGHT),
        Field.new(FieldElement.ROTATE, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.RIGHT),
        Field.new(),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(),
        Field.new(FieldElement.HOLE),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.FLAG_2),
        Field.new(),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.REPAIR_MOD),
        Field.new(FieldElement.HOLE),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.RIGHT),
    ),
    listOf(
        Field.new(),
        Field.new(FieldElement.FLAG_3),
        Field.new(),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
    ),
    listOf(
        Field.new(FieldElement.REPAIR),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldElement.FLAG_4),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(),
        Field.new(),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
    ),
    listOf(
        Field.new(FieldElement.START_7),
        Field.new(listOf(FieldElement.START_5, FieldElement.WALL), Direction.LEFT),
        Field.new(),
        Field.new(listOf(FieldElement.START_3, FieldElement.WALL), Direction.LEFT),
        Field.new(),
        Field.new(listOf(FieldElement.START_1, FieldElement.WALL), Direction.LEFT),
        Field.new(listOf(FieldElement.START_2, FieldElement.WALL), Direction.LEFT),
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(listOf(FieldElement.START_4, FieldElement.WALL), Direction.RIGHT),
        Field.new(),
        Field.new(FieldElement.START_6),
        Field.new(listOf(FieldElement.START_8, FieldElement.WALL), Direction.LEFT),
    ),
    listOf(
        Field.new(),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(),
        Field.new(),
    )
)
