package apoy2k.robby.model.predef.board

import apoy2k.robby.model.Direction
import apoy2k.robby.model.Field
import apoy2k.robby.model.FieldElement

fun generateDemoBoard() = listOf(
    listOf(
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT),
        Field.new(FieldElement.WALL, Direction.UP),
        Field.new(FieldElement.WALL, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.UP, Direction.DOWN),
    ),
    listOf(
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.WALL, Direction.LEFT, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.UP),
        Field.new(FieldElement.BELT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.UP),
    ),
    listOf(
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.LEFT),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP, Direction.LEFT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.LEFT, Direction.RIGHT),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.UP, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.LEFT, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.UP, Direction.LEFT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.RIGHT, Direction.LEFT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.BELT, Direction.DOWN, Direction.LEFT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.LEFT),
        Field.new(FieldElement.BELT_2, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.UP),
    ),
    listOf(
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.LEFT),
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.LEFT),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.LEFT, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.LEFT, Direction.DOWN),
    ),
    listOf(
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.LEFT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.LEFT, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.LEFT, Direction.UP),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.LEFT, Direction.UP, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.UP, Direction.LEFT, Direction.RIGHT, Direction.DOWN),
        Field.new(FieldElement.BELT_2, Direction.DOWN, Direction.LEFT, Direction.UP, Direction.RIGHT),
        Field.new(FieldElement.BELT_2, Direction.RIGHT, Direction.LEFT, Direction.UP, Direction.DOWN),
        Field.new(FieldElement.LASER, Direction.LEFT),
    ),
    listOf(
        Field.new(FieldElement.LASER, Direction.UP),
        Field.new(FieldElement.LASER, Direction.RIGHT),
        Field.new(FieldElement.LASER, Direction.DOWN),
        Field.new(FieldElement.LASER_2, Direction.LEFT),
        Field.new(FieldElement.LASER_2, Direction.UP),
        Field.new(FieldElement.LASER_2, Direction.RIGHT),
        Field.new(FieldElement.LASER_2, Direction.DOWN),
        Field.new(FieldElement.ROTATE, Direction.LEFT),
        Field.new(FieldElement.ROTATE, Direction.RIGHT),
        Field.new(FieldElement.PUSHER, Direction.LEFT),
        Field.new(FieldElement.PUSHER, Direction.UP),
        Field.new(FieldElement.PUSHER, Direction.RIGHT),
    ),
    listOf(
        Field.new(FieldElement.PUSHER, Direction.DOWN),
        Field.new(FieldElement.FLAG),
        Field.new(FieldElement.REPAIR),
        Field.new(FieldElement.REPAIR_MOD),
        Field.new(FieldElement.HOLE),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
        Field.new(),
    )
)
