version: "3.9"

services:
  app:
    container_name: robby
    build: .
    restart: unless-stopped
    ports:
      - "${EXPOSE_PORT}:8080"
    environment:
      JAVA_OPTS: "${JAVA_OPTS}"
      DATABASE_PATH: /app/robby.db
    volumes:
      - ./robby.db:/app/robby.db
