version: "3.9"

services:
  app:
    container_name: robby
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_PATH: /app/robby.db
    volumes:
      - ./robby.db:/app/robby.db

  adminer:
    image: adminer
    ports:
      - "8335:8080"
    volumes:
      - ./robby.db:/app/robby.db
