version: "3.9"

services:
  app:
    container_name: robby
    build: .
    restart: unless-stopped
    ports:
      - "63378:8081"
    environment:
      JAVA_OPTS: "${ROBBY_JAVA_OPTS}"
      DATABASE_PATH: /app/robby.db
    volumes:
      - robby.db:/app/robby.db
