services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./robby.db:/app/robby.db

  adminer:
    image: adminer
    ports:
      - "8335:8080"
    volumes:
      - ./robby.db:/robby.db
      - ./adminer-plugin-loginless.php:/var/www/html/plugins-enabled/login-password-less.php
