package apoy2k.robby.model

import java.util.*

enum class Movement {
    STRAIGHT,
    STRAIGHT_2,
    STRAIGHT_3,
    TURN_LEFT,
    TURN_RIGHT,
    TURN_180,
    BACKWARDS,
}

data class MovementCard(val movement: Movement, val priority: Int) {
    val id: UUID = UUID.randomUUID()
    var player: Player? = null
}

val DEFAULT_FULL_DECK = listOf(
    MovementCard(Movement.STRAIGHT, 490),
    MovementCard(Movement.STRAIGHT, 500),
    MovementCard(Movement.STRAIGHT, 510),
    MovementCard(Movement.STRAIGHT, 520),
    MovementCard(Movement.STRAIGHT, 530),
    MovementCard(Movement.STRAIGHT, 540),
    MovementCard(Movement.STRAIGHT, 550),
    MovementCard(Movement.STRAIGHT, 560),
    MovementCard(Movement.STRAIGHT, 570),
    MovementCard(Movement.STRAIGHT, 580),
    MovementCard(Movement.STRAIGHT, 590),
    MovementCard(Movement.STRAIGHT, 600),
    MovementCard(Movement.STRAIGHT, 610),
    MovementCard(Movement.STRAIGHT, 620),
    MovementCard(Movement.STRAIGHT, 630),
    MovementCard(Movement.STRAIGHT, 640),
    MovementCard(Movement.STRAIGHT, 650),
    MovementCard(Movement.STRAIGHT, 660),

    MovementCard(Movement.STRAIGHT_2, 670),
    MovementCard(Movement.STRAIGHT_2, 680),
    MovementCard(Movement.STRAIGHT_2, 690),
    MovementCard(Movement.STRAIGHT_2, 700),
    MovementCard(Movement.STRAIGHT_2, 710),
    MovementCard(Movement.STRAIGHT_2, 720),
    MovementCard(Movement.STRAIGHT_2, 730),
    MovementCard(Movement.STRAIGHT_2, 740),
    MovementCard(Movement.STRAIGHT_2, 750),
    MovementCard(Movement.STRAIGHT_2, 760),
    MovementCard(Movement.STRAIGHT_2, 770),
    MovementCard(Movement.STRAIGHT_2, 780),

    MovementCard(Movement.STRAIGHT_3, 790),
    MovementCard(Movement.STRAIGHT_3, 800),
    MovementCard(Movement.STRAIGHT_3, 810),
    MovementCard(Movement.STRAIGHT_3, 820),
    MovementCard(Movement.STRAIGHT_3, 830),
    MovementCard(Movement.STRAIGHT_3, 840),

    MovementCard(Movement.BACKWARDS, 430),
    MovementCard(Movement.BACKWARDS, 440),
    MovementCard(Movement.BACKWARDS, 450),
    MovementCard(Movement.BACKWARDS, 460),
    MovementCard(Movement.BACKWARDS, 470),
    MovementCard(Movement.BACKWARDS, 480),

    MovementCard(Movement.TURN_RIGHT, 80),
    MovementCard(Movement.TURN_RIGHT, 100),
    MovementCard(Movement.TURN_RIGHT, 120),
    MovementCard(Movement.TURN_RIGHT, 140),
    MovementCard(Movement.TURN_RIGHT, 160),
    MovementCard(Movement.TURN_RIGHT, 180),
    MovementCard(Movement.TURN_RIGHT, 200),
    MovementCard(Movement.TURN_RIGHT, 220),
    MovementCard(Movement.TURN_RIGHT, 240),
    MovementCard(Movement.TURN_RIGHT, 260),
    MovementCard(Movement.TURN_RIGHT, 280),
    MovementCard(Movement.TURN_RIGHT, 300),
    MovementCard(Movement.TURN_RIGHT, 320),
    MovementCard(Movement.TURN_RIGHT, 340),
    MovementCard(Movement.TURN_RIGHT, 360),
    MovementCard(Movement.TURN_RIGHT, 380),
    MovementCard(Movement.TURN_RIGHT, 400),
    MovementCard(Movement.TURN_RIGHT, 420),

    MovementCard(Movement.TURN_LEFT, 70),
    MovementCard(Movement.TURN_LEFT, 90),
    MovementCard(Movement.TURN_LEFT, 110),
    MovementCard(Movement.TURN_LEFT, 130),
    MovementCard(Movement.TURN_LEFT, 150),
    MovementCard(Movement.TURN_LEFT, 170),
    MovementCard(Movement.TURN_LEFT, 190),
    MovementCard(Movement.TURN_LEFT, 210),
    MovementCard(Movement.TURN_LEFT, 230),
    MovementCard(Movement.TURN_LEFT, 250),
    MovementCard(Movement.TURN_LEFT, 270),
    MovementCard(Movement.TURN_LEFT, 290),
    MovementCard(Movement.TURN_LEFT, 310),
    MovementCard(Movement.TURN_LEFT, 330),
    MovementCard(Movement.TURN_LEFT, 350),
    MovementCard(Movement.TURN_LEFT, 370),
    MovementCard(Movement.TURN_LEFT, 390),
    MovementCard(Movement.TURN_LEFT, 410),

    MovementCard(Movement.TURN_180, 10),
    MovementCard(Movement.TURN_180, 20),
    MovementCard(Movement.TURN_180, 30),
    MovementCard(Movement.TURN_180, 40),
    MovementCard(Movement.TURN_180, 50),
    MovementCard(Movement.TURN_180, 60),
)
