package apoy2k.robby.model.predef.deck

import apoy2k.robby.model.Movement
import apoy2k.robby.model.MovementCard

fun generateStandardDeck() = mutableListOf(
    MovementCard.new(Movement.STRAIGHT, 490),
    MovementCard.new(Movement.STRAIGHT, 500),
    MovementCard.new(Movement.STRAIGHT, 510),
    MovementCard.new(Movement.STRAIGHT, 520),
    MovementCard.new(Movement.STRAIGHT, 530),
    MovementCard.new(Movement.STRAIGHT, 540),
    MovementCard.new(Movement.STRAIGHT, 550),
    MovementCard.new(Movement.STRAIGHT, 560),
    MovementCard.new(Movement.STRAIGHT, 570),
    MovementCard.new(Movement.STRAIGHT, 580),
    MovementCard.new(Movement.STRAIGHT, 590),
    MovementCard.new(Movement.STRAIGHT, 600),
    MovementCard.new(Movement.STRAIGHT, 610),
    MovementCard.new(Movement.STRAIGHT, 620),
    MovementCard.new(Movement.STRAIGHT, 630),
    MovementCard.new(Movement.STRAIGHT, 640),
    MovementCard.new(Movement.STRAIGHT, 650),
    MovementCard.new(Movement.STRAIGHT, 660),

    MovementCard.new(Movement.STRAIGHT_2, 670),
    MovementCard.new(Movement.STRAIGHT_2, 680),
    MovementCard.new(Movement.STRAIGHT_2, 690),
    MovementCard.new(Movement.STRAIGHT_2, 700),
    MovementCard.new(Movement.STRAIGHT_2, 710),
    MovementCard.new(Movement.STRAIGHT_2, 720),
    MovementCard.new(Movement.STRAIGHT_2, 730),
    MovementCard.new(Movement.STRAIGHT_2, 740),
    MovementCard.new(Movement.STRAIGHT_2, 750),
    MovementCard.new(Movement.STRAIGHT_2, 760),
    MovementCard.new(Movement.STRAIGHT_2, 770),
    MovementCard.new(Movement.STRAIGHT_2, 780),

    MovementCard.new(Movement.STRAIGHT_3, 790),
    MovementCard.new(Movement.STRAIGHT_3, 800),
    MovementCard.new(Movement.STRAIGHT_3, 810),
    MovementCard.new(Movement.STRAIGHT_3, 820),
    MovementCard.new(Movement.STRAIGHT_3, 830),
    MovementCard.new(Movement.STRAIGHT_3, 840),

    MovementCard.new(Movement.BACKWARDS, 430),
    MovementCard.new(Movement.BACKWARDS, 440),
    MovementCard.new(Movement.BACKWARDS, 450),
    MovementCard.new(Movement.BACKWARDS, 460),
    MovementCard.new(Movement.BACKWARDS, 470),
    MovementCard.new(Movement.BACKWARDS, 480),

    MovementCard.new(Movement.TURN_RIGHT, 80),
    MovementCard.new(Movement.TURN_RIGHT, 100),
    MovementCard.new(Movement.TURN_RIGHT, 120),
    MovementCard.new(Movement.TURN_RIGHT, 140),
    MovementCard.new(Movement.TURN_RIGHT, 160),
    MovementCard.new(Movement.TURN_RIGHT, 180),
    MovementCard.new(Movement.TURN_RIGHT, 200),
    MovementCard.new(Movement.TURN_RIGHT, 220),
    MovementCard.new(Movement.TURN_RIGHT, 240),
    MovementCard.new(Movement.TURN_RIGHT, 260),
    MovementCard.new(Movement.TURN_RIGHT, 280),
    MovementCard.new(Movement.TURN_RIGHT, 300),
    MovementCard.new(Movement.TURN_RIGHT, 320),
    MovementCard.new(Movement.TURN_RIGHT, 340),
    MovementCard.new(Movement.TURN_RIGHT, 360),
    MovementCard.new(Movement.TURN_RIGHT, 380),
    MovementCard.new(Movement.TURN_RIGHT, 400),
    MovementCard.new(Movement.TURN_RIGHT, 420),

    MovementCard.new(Movement.TURN_LEFT, 70),
    MovementCard.new(Movement.TURN_LEFT, 90),
    MovementCard.new(Movement.TURN_LEFT, 110),
    MovementCard.new(Movement.TURN_LEFT, 130),
    MovementCard.new(Movement.TURN_LEFT, 150),
    MovementCard.new(Movement.TURN_LEFT, 170),
    MovementCard.new(Movement.TURN_LEFT, 190),
    MovementCard.new(Movement.TURN_LEFT, 210),
    MovementCard.new(Movement.TURN_LEFT, 230),
    MovementCard.new(Movement.TURN_LEFT, 250),
    MovementCard.new(Movement.TURN_LEFT, 270),
    MovementCard.new(Movement.TURN_LEFT, 290),
    MovementCard.new(Movement.TURN_LEFT, 310),
    MovementCard.new(Movement.TURN_LEFT, 330),
    MovementCard.new(Movement.TURN_LEFT, 350),
    MovementCard.new(Movement.TURN_LEFT, 370),
    MovementCard.new(Movement.TURN_LEFT, 390),
    MovementCard.new(Movement.TURN_LEFT, 410),

    MovementCard.new(Movement.TURN_180, 10),
    MovementCard.new(Movement.TURN_180, 20),
    MovementCard.new(Movement.TURN_180, 30),
    MovementCard.new(Movement.TURN_180, 40),
    MovementCard.new(Movement.TURN_180, 50),
    MovementCard.new(Movement.TURN_180, 60),
).shuffled().toMutableList()
