package apoy2k.robby.model.predef.board

import apoy2k.robby.model.Direction
import apoy2k.robby.model.Field
import apoy2k.robby.model.FieldType

val CHOP_SHOP_BOARD = listOf(
    listOf(
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(FieldType.BELT, Direction.DOWN),
        Field(FieldType.BELT, Direction.UP),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(FieldType.REPAIR)
    ),
    listOf(
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.LASER_2, Direction.DOWN),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT, Direction.DOWN),
        Field(FieldType.BELT, Direction.UP),
        Field(),
        Field(),
        Field(),
        Field(FieldType.HOLE),
        Field(),
    ),
    listOf(
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.REPAIR_MOD),
        Field(FieldType.WALL, Direction.DOWN),
        Field(FieldType.LASER, Direction.LEFT),
        Field(FieldType.ROTATE, Direction.LEFT),
        Field(FieldType.ROTATE, Direction.RIGHT),
        Field(),
        Field(),
        Field(FieldType.WALL, Direction.RIGHT),
        Field(FieldType.WALL, Direction.DOWN),
        Field(FieldType.WALL, Direction.RIGHT)
    ),
    listOf(
        Field(FieldType.BELT, Direction.RIGHT),
        Field(FieldType.BELT, Direction.RIGHT),
        Field(FieldType.BELT, Direction.RIGHT),
        Field(),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT, Direction.UP),
        Field(FieldType.BELT_2, Direction.RIGHT),
        Field(FieldType.BELT_2, Direction.RIGHT),
    ),
    listOf(
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(),
        Field(FieldType.ROTATE, Direction.RIGHT),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(FieldType.BELT_2, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.RIGHT),
    ),
    listOf(
        Field(),
        Field(),
        Field(FieldType.HOLE),
        Field(FieldType.ROTATE, Direction.LEFT),
        Field(),
        Field(),
        Field(FieldType.REPAIR_MOD),
        Field(FieldType.BELT, Direction.DOWN),
        Field(FieldType.WALL, Direction.LEFT, Direction.UP),
        Field(FieldType.BELT_2, Direction.UP, Direction.LEFT),
        Field(FieldType.BELT_2, Direction.LEFT),
        Field(FieldType.BELT_2, Direction.LEFT),
    ),
    listOf(
        Field(),
        Field(),
        Field(),
        Field(FieldType.LASER_2, Direction.UP),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT, Direction.UP),
        Field(FieldType.ROTATE, Direction.LEFT),
        Field(FieldType.BELT, Direction.RIGHT),
        Field(FieldType.BELT, Direction.RIGHT),
        Field(FieldType.BELT, Direction.RIGHT),
        Field(FieldType.BELT, Direction.RIGHT),
    ),
    listOf(
        Field(FieldType.WALL, Direction.LEFT),
        Field(FieldType.LASER, Direction.DOWN),
        Field(),
        Field(),
        Field(),
        Field(FieldType.HOLE),
        Field(FieldType.BELT, Direction.UP),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(FieldType.FLAG),
    ),
    listOf(
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.ROTATE, Direction.LEFT),
        Field(),
        Field(FieldType.LASER, Direction.RIGHT),
        Field(FieldType.ROTATE, Direction.RIGHT),
        Field(FieldType.WALL, Direction.RIGHT),
        Field(),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT),
    ),
    listOf(
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.HOLE),
        Field(FieldType.BELT, Direction.UP),
        Field(FieldType.FLAG),
        Field(),
        Field(FieldType.BELT, Direction.UP),
        Field(FieldType.REPAIR_MOD),
        Field(FieldType.HOLE),
        Field(FieldType.BELT, Direction.LEFT),
        Field(FieldType.BELT, Direction.LEFT, Direction.UP),
        Field(FieldType.WALL, Direction.RIGHT),
    ),
    listOf(
        Field(),
        Field(FieldType.FLAG),
        Field(),
        Field(FieldType.BELT, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
        Field(FieldType.BELT, Direction.UP),
        Field(),
        Field(),
        Field(),
        Field(FieldType.BELT, Direction.UP),
        Field(),
    ),
    listOf(
        Field(FieldType.REPAIR),
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(FieldType.BELT, Direction.UP),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(FieldType.BELT, Direction.UP),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(FieldType.FLAG),
        Field(FieldType.BELT, Direction.UP),
        Field(),
    ),
    listOf(
        Field(),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(FieldType.WALL, Direction.UP),
        Field(),
        Field(),
    ),
    listOf(
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
        Field(),
    ),
    listOf(
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
        Field(FieldType.WALL, Direction.LEFT),
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
        Field(),
        Field(FieldType.WALL, Direction.LEFT),
    ),
    listOf(
        Field(),
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(FieldType.WALL, Direction.DOWN),
        Field(),
        Field(),
    )
)